export const CREATE_SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS trip (
    trip_id TEXT PRIMARY KEY,
    started_at_ms INTEGER NOT NULL,
    ended_at_ms INTEGER,
    route_number TEXT NOT NULL,
    direction_code TEXT NOT NULL,
    window_code TEXT NOT NULL,
    status TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS gps_point (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_id TEXT NOT NULL,
    timestamp_ms INTEGER NOT NULL,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    accuracy_m REAL,
    speed_mps REAL,
    heading_deg REAL,
    derived_speed_mps REAL,
    derived_heading_deg REAL,
    FOREIGN KEY(trip_id) REFERENCES trip(trip_id) ON DELETE CASCADE
  );`,
  `CREATE INDEX IF NOT EXISTS idx_gps_point_trip_ts ON gps_point(trip_id, timestamp_ms);`,
  `CREATE TABLE IF NOT EXISTS stop (
    stop_id INTEGER PRIMARY KEY,
    stop_name TEXT NOT NULL,
    lat REAL NOT NULL,
    lon REAL NOT NULL,
    stop_sequence INTEGER NOT NULL,
    direction_code TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS stop_event (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trip_id TEXT NOT NULL,
    stop_id INTEGER NOT NULL,
    event_type TEXT NOT NULL,
    timestamp_ms INTEGER NOT NULL,
    dist_m REAL NOT NULL,
    lat REAL,
    lon REAL,
    FOREIGN KEY(trip_id) REFERENCES trip(trip_id) ON DELETE CASCADE,
    FOREIGN KEY(stop_id) REFERENCES stop(stop_id)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_stop_event_trip_ts ON stop_event(trip_id, timestamp_ms);`,
];

export const CREATE_V1_TABLE_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS schema_meta (
    schema_version INTEGER NOT NULL,
    installed_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS devices (
    device_id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    platform TEXT NOT NULL,
    os_version TEXT NOT NULL,
    model TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS routes (
    route_id TEXT PRIMARY KEY,
    route_number TEXT NOT NULL,
    name TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS route_variants (
    variant_id TEXT PRIMARY KEY,
    route_id TEXT NOT NULL,
    direction TEXT NOT NULL,
    time_period TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    FOREIGN KEY(route_id) REFERENCES routes(route_id)
  );`,
  `CREATE TABLE IF NOT EXISTS stops (
    stop_id TEXT PRIMARY KEY,
    variant_id TEXT NOT NULL,
    stop_order INTEGER NOT NULL,
    name TEXT NOT NULL,
    lat REAL NOT NULL,
    lng REAL NOT NULL,
    radius_m REAL NOT NULL,
    FOREIGN KEY(variant_id) REFERENCES route_variants(variant_id)
  );`,
  `CREATE TABLE IF NOT EXISTS trip_sessions (
    trip_id TEXT PRIMARY KEY,
    device_id TEXT NOT NULL,
    variant_id TEXT NOT NULL,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    timezone TEXT NOT NULL,
    app_version TEXT NOT NULL,
    time_bucket TEXT NOT NULL,
    notes TEXT,
    experiment_variant TEXT,
    task_restart_count INTEGER,
    battery_start_pct INTEGER,
    battery_end_pct INTEGER,
    battery_drain_pct INTEGER,
    max_gap_sec REAL,
    FOREIGN KEY(device_id) REFERENCES devices(device_id),
    FOREIGN KEY(variant_id) REFERENCES route_variants(variant_id)
  );`,
  `CREATE TABLE IF NOT EXISTS gps_points (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    point_id TEXT UNIQUE,
    trip_id TEXT NOT NULL,
    ts TEXT,
    timestamp_ms INTEGER,
    lat REAL NOT NULL,
    lng REAL,
    lon REAL,
    accuracy_m REAL,
    altitude_m REAL,
    speed_mps REAL,
    bearing_deg REAL,
    heading_deg REAL,
    derived_speed_mps REAL,
    derived_heading_deg REAL,
    provider_speed_mps REAL,
    provider_heading_deg REAL,
    is_filtered INTEGER NOT NULL DEFAULT 0,
    filter_reason TEXT,
    smoothed_lat REAL,
    smoothed_lng REAL,
    smoothed_lon REAL,
    smoothed_speed_mps REAL,
    FOREIGN KEY(trip_id) REFERENCES trip_sessions(trip_id)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_gps_points_trip_ts ON gps_points(trip_id, ts);`,
  `CREATE INDEX IF NOT EXISTS idx_gps_points_trip_timestamp_ms ON gps_points(trip_id, timestamp_ms);`,
  `CREATE TABLE IF NOT EXISTS stop_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_id TEXT UNIQUE,
    trip_id TEXT NOT NULL,
    stop_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    timestamp_ms INTEGER,
    ts TEXT,
    dist_m REAL,
    dist_to_stop_m REAL,
    lat REAL,
    lon REAL,
    speed_mps REAL,
    accuracy_m REAL,
    FOREIGN KEY(trip_id) REFERENCES trip_sessions(trip_id),
    FOREIGN KEY(stop_id) REFERENCES stops(stop_id)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_stop_events_trip_ts ON stop_events(trip_id, ts);`,
  `CREATE INDEX IF NOT EXISTS idx_stop_events_trip_timestamp_ms ON stop_events(trip_id, timestamp_ms);`,
  `CREATE TABLE IF NOT EXISTS stop_states (
    trip_id TEXT NOT NULL,
    stop_id TEXT NOT NULL,
    state TEXT NOT NULL,
    entered_at_ms INTEGER,
    dwell_at_ms INTEGER,
    exit_candidate_count INTEGER NOT NULL DEFAULT 0,
    updated_at_ms INTEGER NOT NULL,
    PRIMARY KEY (trip_id, stop_id),
    FOREIGN KEY(trip_id) REFERENCES trip_sessions(trip_id),
    FOREIGN KEY(stop_id) REFERENCES stops(stop_id)
  );`,
  `CREATE TABLE IF NOT EXISTS segment_times (
    segment_id TEXT PRIMARY KEY,
    trip_id TEXT NOT NULL,
    from_stop_id TEXT NOT NULL,
    to_stop_id TEXT NOT NULL,
    depart_ms INTEGER,
    arrive_ms INTEGER,
    travel_time_s REAL,
    start_ts TEXT NOT NULL,
    end_ts TEXT NOT NULL,
    travel_time_sec INTEGER NOT NULL,
    distance_m REAL NOT NULL,
    avg_speed_mps REAL,
    p95_speed_mps REAL,
    mean_accuracy_m REAL,
    quality_flag TEXT,
    point_count INTEGER,
    max_gap_sec REAL,
    p95_accuracy_m REAL,
    min_accuracy_m REAL,
    FOREIGN KEY(trip_id) REFERENCES trip_sessions(trip_id),
    FOREIGN KEY(from_stop_id) REFERENCES stops(stop_id),
    FOREIGN KEY(to_stop_id) REFERENCES stops(stop_id)
  );`,
  `CREATE INDEX IF NOT EXISTS idx_segment_times_trip ON segment_times(trip_id);`,
  `CREATE TABLE IF NOT EXISTS config (
    key TEXT PRIMARY KEY,
    value TEXT
  );`,
];
